import Head from "next/head";

import styles from "@/styles/Home.module.scss";

import AnimatedText from "@/components/AnimatedTextTutorial/page";

import { instrumentText } from "../../Lib/Fonts/font";

export default function Home() {
  return (
    <>
      <Head>
        <title>Text Load In Animation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AnimatedText
          text={`You need this text animation on your site`}
          delay={0.5}
          duration={1.25}
          staggerDuration={0.05}
          targetedElement={"word"}
          className={instrumentText.className}
        />
      </main>
    </>
  );
}
